export const countries: { [key: string]: string } = {
  AC: "Ascension (Vereinigtes Königreich)",
  AD: "Andorra",
  AE: "Vereinigte Arabische Emirate",
  AF: "Afghanistan",
  AG: "Antigua und Barbuda",
  AI: "Anguilla (Vereinigtes Königreich)",
  AL: "Albanien",
  AM: "Armenien",
  AO: "Angola",
  AQ: "Antarktis",
  AR: "Argentinien",
  AS: "Amerikanisch-Samoa",
  AT: "Österreich",
  AU: "Australien",
  AW: "Aruba (Niederlande)",
  AX: "Åland (Finnland)",
  AZ: "Aserbaidschan",
  BA: "Bosnien und Herzegowina",
  BB: "Barbados",
  BD: "Bangladesch",
  BE: "Belgien",
  BF: "Burkina Faso",
  BG: "Bulgarien",
  BH: "Bahrain",
  BI: "Burundi",
  BJ: "Benin",
  BL: "Saint-Barthélemy (Frankreich)",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivien",
  BQ: "Bonaire, Saba, Sint Eustatius (Niederlande)",
  BR: "Brasilien",
  BS: "Bahamas",
  BT: "Bhutan",
  BV: "Bouvetinsel (Norwegen)",
  BW: "Botswana",
  BY: "Belarus",
  BZ: "Belize",
  CA: "Kanada",
  CC: "Kokosinseln (Australien)",
  CD: "Demokratische Republik Kongo",
  CF: "Zentralafrikanische Republik",
  CG: "Republik Kongo",
  CH: "Schweiz",
  CI: "Elfenbeinküste",
  CK: "Cookinseln (Neuseeland)",
  CL: "Chile",
  CM: "Kamerun",
  CN: "Volksrepublik China",
  CO: "Kolumbien",
  CP: "Clipperton-Insel (Frankreich)",
  CR: "Costa Rica",
  CU: "Kuba",
  CV: "Kap Verde",
  CW: "Curaçao (Niederlande)",
  CX: "Weihnachtsinsel (Australien)",
  CY: "Zypern",
  CZ: "Tschechien",
  DE: "Deutschland",
  DG: "Diego Garcia (Vereinigtes Königreich)",
  DJ: "Dschibuti",
  DK: "Dänemark",
  DM: "Dominica",
  DO: "Dominikanische Republik",
  DZ: "Algerien",
  EA: "Ceuta und Melilla (Spanien)",
  EC: "Ecuador",
  EE: "Estland",
  EG: "Ägypten",
  EH: "Westsahara",
  ER: "Eritrea",
  ES: "Spanien",
  ET: "Äthiopien",
  EU: "Europäische Union",
  FI: "Finnland",
  FJ: "Fidschi",
  FK: "Falklandinseln (Vereinigtes Königreich)",
  FM: "Föderierte Staaten von Mikronesien",
  FO: "Färöer Inseln (Dänemark)",
  FR: "Frankreich",
  GA: "Gabun",
  GB: "Vereinigtes Königreich Großbritannien und Nordirland",
  GD: "Grenada",
  GE: "Georgien",
  GF: "Französisch-Guayana (Frankreich)",
  GG: "Guernsey (Vereinigtes Königreich)",
  GH: "Ghana",
  GI: "Gibraltar (Vereinigtes Königreich)",
  GL: "Grönland (Dänemark)",
  GM: "Gambia",
  GN: "Guinea",
  GP: "Guadeloupe (Frankreich)",
  GQ: "Äquatorialguinea",
  GR: "Griechenland",
  GS: "Südgeorgien und die Südlichen Sandwichinseln (Vereinigtes Königreich)",
  GT: "Guatemala",
  GU: "Guam (Vereinigte Staaten)",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HK: "Hongkong (Volksrepublik China)",
  HM: "Heard- und McDonald-Inseln (Australien)",
  HN: "Honduras",
  HR: "Kroatien",
  HT: "Haiti",
  HU: "Ungarn",
  IC: "Kanarische Inseln (Spanien)",
  ID: "Indonesien",
  IE: "Irland",
  IL: "Israel",
  IM: "Isle of Man",
  IN: "Indien",
  IO: "Britisches Territorium im Indischen Ozean (Vereinigtes Königreich)",
  IQ: "Irak",
  IR: "Iran",
  IS: "Island",
  IT: "Italien",
  JE: "Jersey (Vereinigtes Königreich)",
  JM: "Jamaika",
  JO: "Jordanien",
  JP: "Japan",
  KE: "Kenia",
  KI: "Kiribati",
  KG: "Kirgisistan",
  KH: "Kambodscha",
  KM: "Komoren",
  KN: "St. Kitts und Nevis",
  KP: "Demokratische Volksrepublik Korea",
  KR: "Republik Korea",
  KW: "Kuwait",
  KY: "Cayman Islands (Vereinigtes Königreich)",
  KZ: "Kasachstan",
  LA: "Laos",
  LB: "Libanon",
  LC: "St. Lucia",
  LI: "Liechtenstein",
  LK: "Sri Lanka",
  LR: "Liberia",
  LS: "Lesotho",
  LT: "Litauen",
  LU: "Luxemburg",
  LV: "Lettland",
  LY: "Libyen",
  MA: "Marokko",
  MC: "Monaco",
  MD: "Moldau",
  ME: "Montenegro",
  MF: "Saint-Martin (Frankreich)",
  MG: "Madagaskar",
  MH: "Marshallinseln",
  MK: "Nordmazedonien",
  ML: "Mali",
  MM: "Myanmar",
  MN: "Mongolei",
  MO: "Macau (Volksrepublik China)",
  MP: "Nördliche Marianen (Vereinigte Staaten)",
  MQ: "Martinique (Frankreich)",
  MR: "Mauretanien",
  MS: "Montserrat (Vereinigtes Königreich)",
  MT: "Malta",
  MU: "Mauritius",
  MV: "Malediven",
  MW: "Malawi",
  MX: "Mexiko",
  MY: "Malaysia",
  MZ: "Mosambik",
  NA: "Namibia",
  NC: "Neukaledonien (Frankreich)",
  NE: "Niger",
  NF: "Norfolkinsel (Australien)",
  NG: "Nigeria",
  NI: "Nicaragua",
  NL: "Niederlande",
  NO: "Norwegen",
  NP: "Nepal",
  NR: "Nauru",
  NU: "Niue (Neuseeland)",
  NZ: "Neuseeland",
  OM: "Oman",
  PA: "Panama",
  PE: "Peru",
  PF: "Französisch-Polynesien (Frankreich)",
  PG: "Papua-Neuguinea",
  PH: "Philippinen",
  PK: "Pakistan",
  PL: "Polen",
  PM: "Saint-Pierre und Miquelon (Frankreich)",
  PN: "Pitcairninseln (Vereinigtes Königreich)",
  PR: "Puerto Rico (Vereinigte Staaten)",
  PS: "Palästina",
  PT: "Portugal",
  PW: "Palau",
  PY: "Paraguay",
  QA: "Katar",
  RE: "Réunion (Frankreich)",
  RO: "Rumänien",
  RS: "Serbien",
  RU: "Russland",
  RW: "Ruanda",
  SA: "Saudi-Arabien",
  SB: "Salomonen",
  SC: "Seychellen",
  SD: "Sudan",
  SE: "Schweden",
  SG: "Singapur",
  SH: "St. Helena, Ascension und Tristan da Cunha (Vereinigtes Königreich)",
  SI: "Slowenien",
  SJ: "Spitzbergen und Jan Mayen (Norwegen)",
  SK: "Slowakei",
  SL: "Sierra Leone",
  SM: "San Marino",
  SN: "Senegal",
  SO: "Somalia",
  SR: "Suriname",
  SS: "Südsudan",
  ST: "São Tomé und Príncipe",
  SV: "El Salvador",
  SX: "Sint Maarten (Niederlande)",
  SY: "Syrien",
  SZ: "Eswatini",
  TA: "Tristan da Cunha (Vereinigtes Königreich)",
  TC: "Turks- und Caicosinseln (Vereinigtes Königreich)",
  TD: "Tschad",
  TF: "Französische Süd- und Antarktisgebiete (Frankreich)",
  TG: "Togo",
  TH: "Thailand",
  TJ: "Tadschikistan",
  TK: "Tokelau (Neuseeland)",
  TL: "Osttimor",
  TM: "Turkmenistan",
  TN: "Tunesien",
  TO: "Tonga",
  TR: "Türkei",
  TT: "Trinidad und Tobago",
  TV: "Tuvalu",
  TW: "Taiwan",
  TZ: "Tansania",
  UA: "Ukraine",
  UG: "Uganda",
  UM: "United States Minor Outlying Islands (Vereinigte Staaten)",
  US: "Vereinigte Staaten von Amerika",
  UY: "Uruguay",
  UZ: "Usbekistan",
  VA: "Vatikanstadt",
  VC: "St. Vincent und die Grenadinen",
  VE: "Venezuela",
  VG: "Britische Jungferninseln (Vereinigtes Königreich)",
  VI: "Amerikanische Jungferninseln (Vereinigte Staaten)",
  VN: "Vietnam",
  VU: "Vanuatu",
  WF: "Wallis und Futuna (Frankreich)",
  WS: "Samoa",
  YE: "Jemen",
  YT: "Mayotte (Frankreich)",
  ZA: "Südafrika",
  ZM: "Sambia",
  ZW: "Simbabwe",
};
